version: '3.4'

services:
    app:
        build: .
        ports:
            - 127.0.0.1:8400:6000
        environment:
            - SWOOLE_PORT=6000
            - SWOOLE_WORKER=20
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=database
        depends_on:
            - mysql_db

    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 127.0.0.1:3306:3306
        environment:
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: root

volumes:
    mysql_db:
        driver: local